### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by meyt** [Carrene/nanohttp#111]
`nanohttp` older versions cannot install anymore, because of dependencies are specified with `>=` and makes incompatibility if one of them have major release.

e.i: Versions before latest `pymlconf>1.*` migration are breaks:
```
  File "[...]/venv/lib/python3.6/site-packages/nanohttp/configuration.py", line 5, in <module>
    settings = pymlconf.DeferredConfigManager()
AttributeError: module 'pymlconf' has no attribute 'DeferredConfigManager'
```

https://www.python.org/dev/peps/pep-0440/#compatible-release

**Comment by pylover** [comment]
Current nanohttp is compatible with the latest pymlconf.

So, you may upgrade to a major release, or limit it in your setup.py.
