### ISSUE TITLE
Unused parts

### ISSUE THREAD

**Issue by meyt** [Carrene/nanohttp#122]
Unused variable:
https://github.com/Carrene/nanohttp/blob/2d306d8a8e9e4d5e2e76da3587df711244116fb8/nanohttp/decorators.py#L46

Re-declared without usage:
https://github.com/Carrene/nanohttp/blob/2d306d8a8e9e4d5e2e76da3587df711244116fb8/nanohttp/exceptions.py#L10
https://github.com/Carrene/nanohttp/blob/2d306d8a8e9e4d5e2e76da3587df711244116fb8/nanohttp/exceptions.py#L30

**Comment by pylover** [comment]
Disagree with the third one. But a lot of thanks for the others. 

Mr, Sherlock Mahdi Holms.

**Comment by meyt** [comment]
Third part is an evidence for No.2
