### ISSUE TITLE
Empty request body when using prevent_form decorator

### ISSUE THREAD

**Issue by ArashFatahzade** [Carrene/nanohttp#123]
When a method in the controller has `prevent_form` decorator, the request must have an **empty body** or `CONTENT-LENGTH` must exist with zero value.
Is this ok? Or We can accept any request without body?

**Comment by pylover** [comment]
Content-Length should not be checked when the request has no payload.

**Comment by pylover** [comment]
```
from nanohttp import *


class Root(Controller):
    @action(prevent_form=True)
    def index(self):
        yield 'default'
```

```
curl localhost:8080 -i
```

```
HTTP/1.0 200 OK
Date: Sun, 07 Oct 2018 19:02:24 GMT
Server: WSGIServer/0.2 CPython/3.6.5
```

**Comment by pylover** [comment]
Please try to reproduce the issue before adding.

**Comment by ArashFatahzade** [comment]
The bug occurs when the verb is not `GET`.
Try this:
```python

from nanohttp import *


class Root(RestController):
    @text(prevent_form=True)
    def abc(self):
        return 'default'

```

```bash
curl localhost:8080 -v  -XABC`
```

Response:
```
* Rebuilt URL to: localhost:8080/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> ABC / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
^C
```

Controller hangs in this line:
https://github.com/Carrene/nanohttp/blob/b6bd92022eb4a6a6d9cde9a13f3d06591bdde225/nanohttp/helpers.py#L103

Because  `CONTENT-LENGTH` is None and `CONTENT-TYPE` is not `application/json`, so `cgi.FieldStorage` tries to read the body and hangs there.

**Comment by pylover** [comment]
A very bad bug reporting, which causes wasting a lot of time to understand what happened.

**Comment by pylover** [comment]
Migrated to #124
