### ISSUE TITLE
Dump None type on JSON decorator

### ISSUE THREAD

**Issue by meyt** [Carrene/nanohttp#134]
JSON is now support just `null` values.
> Note that certain previous specifications of JSON constrained a JSON text to be an object or an array.  Implementations that generate only objects or arrays where a JSON text is called for will be interoperable in the sense that all implementations will accept these as conforming JSON texts.
 JSON-text = ws value ws
[rfc7159 ↗️](https://tools.ietf.org/html/rfc7159#section-2)

**Comment by pylover** [comment]
#135
