### ISSUE TITLE
ContextStack should be threadsafe

### ISSUE THREAD

**Issue by memlucky71** [Carrene/nanohttp#46]
With each request in the web, the request is added to a request queue. Then, `Thread pool` chooses a thread  to serve the request and send back the response.
Finally, this thread is added to the thread pool. In nanohttp, whole the concept is managed through the Context. In nanohttp, it is possible to make nested context. For each request, a thread stack is created. 
Since two requests can use a `single context`, this can run into problems. So the context should be handled thread safe using `thread_local`.

**Comment by pylover** [comment]
Please add some descriptions
