### ISSUE TITLE
Handle exception during HTTP streaming

### ISSUE THREAD

**Issue by mehrdad1373pedramfar** [Carrene/nanohttp#91]
Find a way to handle exception while we already called `start_response`.
just now when the error occurs we print out the error and close the connection.

**Comment by ArashFatahzade** [comment]
[https://stackoverflow.com/a/15305631/9624798](https://stackoverflow.com/a/15305631/9624798)

**Comment by ArashFatahzade** [comment]
We decided to implement ` HTTP Trailer`. 
More info: 
[Trailer RFC](https://tools.ietf.org/html/rfc2616#section-14.40)
[Chunked Transfer Coding](https://tools.ietf.org/html/rfc2616#section-3.6.1)

**Comment by mehrdad1373pedramfar** [comment]
This is good for understanding: http://engineering.pivotal.io/post/http-trailers/

**Comment by pylover** [comment]
https://www.python.org/dev/peps/pep-0333/#buffering-and-streaming

**Comment by pylover** [comment]
From PEP#0333

```
However, if exc_info is provided, and the HTTP headers have already been sent, start_response must raise an error, and should raise the exc_info tuple. That is:

raise exc_info[0], exc_info[1], exc_info[2]
This will re-raise the exception trapped by the application, and in principle should abort the application. (It is not safe for the application to attempt error output to the browser once the HTTP headers have already been sent.) The application must not trap any exceptions raised by start_response, if it called start_response with exc_info. Instead, it should allow such exceptions to propagate back to the server or gateway. See Error Handling below, for more details.
```
